services:
  backend:
    container_name: runners-backend
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: unless-stopped
    env_file:
      - config/.env
    volumes:
      - django-static:/app/staticfiles
      - django-media:/mnt/media
    ports:
      - "8000:8000"

  db:
    image: postgres
    container_name: runners-db
    restart: always
    env_file:
      - config/.env
    environment:
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: runners-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - nginx-data:/data
      - letsencrypt-data:/etc/letsencrypt
      - django-static:/mnt/staticfiles
      - django-media:/mnt/media

volumes:
  db-data: {}
  nginx-data: {}
  letsencrypt-data: {}
  django-static: {}
  django-media: {}