services:
  django:
    container_name: django
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: src/Dockerfile
    restart: unless-stopped
    env_file:
      - config/.env
    volumes:
      - django-static:/app/staticfiles
      - django-media:/mnt/media
    ports:
      - "8000:8000"

  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - config/.env
    environment:
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - db-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - config/.env
    volumes:
      - ./data/nginx/templates:/etc/nginx/templates
      - ./data/nginx/html:/usr/share/nginx/html
      - certbot-www:/var/www/certbot

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    env_file:
      - config/.env
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-conf:/etc/letsencrypt
    entrypoint: sh -c "trap exit TERM; while :; do certbot certonly --webroot --webroot-path /var/www/certbot -d $$DOMAIN -d www.$$DOMAIN --email $$LETSENCRYPT_EMAIL --agree-tos --no-eff-email --keep-until-expiring --non-interactive; nginx_pid=$(pgrep nginx) && sleep 12h & wait $!; done"
    depends_on:
      - nginx

volumes:
  db-data: {}
  django-static: {}
  django-media: {}
  certbot-www: { }
  certbot-conf: { }