# Generated by Django 5.0.6 on 2024-07-09 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("rr", models.CharField(blank=True, max_length=250)),
                ("po", models.CharField(blank=True, max_length=250)),
                ("afe", models.CharField(blank=True, max_length=250)),
                ("carrier", models.CharField(blank=True, max_length=250)),
                ("received_transferred", models.CharField(blank=True, max_length=250)),
                ("joints", models.IntegerField()),
                ("footage", models.DecimalField(decimal_places=4, max_digits=44)),
                ("attachment", models.FileField(upload_to="media/")),
                ("manufacturer", models.CharField(blank=True, max_length=250)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
