# Generated by Django 5.0.6 on 2024-07-09 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_type", models.CharField(blank=True, max_length=250)),
                ("outside_diameter_text", models.CharField(blank=True, max_length=250)),
                ("outside_diameter", models.FloatField(null=True)),
                ("weight_text", models.CharField(blank=True, max_length=250)),
                ("weight", models.FloatField(null=True)),
                ("grade", models.CharField(blank=True, max_length=250)),
                ("coupling", models.CharField(blank=True, max_length=250)),
                ("range", models.CharField(blank=True, max_length=250)),
                ("condition", models.CharField(blank=True, max_length=250)),
                ("remarks", models.CharField(blank=True, max_length=1000)),
                ("foreman", models.CharField(blank=True, max_length=250)),
                ("rack", models.CharField(max_length=250)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
