# Generated by Django 5.0.4 on 2024-05-12 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_type", models.TextField(blank=True)),
                ("outside_diameter", models.TextField(blank=True)),
                ("outside_diameter_inches", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("grade", models.TextField(blank=True)),
                ("coupling", models.TextField(blank=True)),
                ("range", models.TextField(blank=True)),
                ("condition", models.TextField(blank=True)),
                ("remarks", models.TextField(blank=True)),
                ("foreman", models.TextField(blank=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="customers.customer",
                    ),
                ),
            ],
        ),
    ]
